name: "Testing PR events"
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
  pull_request:
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Cat file
      run: |
        cat myfile.txt
        cat secondfile.txt
    - name: Get Branch Name
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "PR source branch: ${BRANCH_NAME}"
        else
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Push triggered on: ${BRANCH_NAME}"
        fi
        BRANCH_SLUG="${BRANCH_NAME//\//_}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV
        echo "CACHE_TAG=${BRANCH_SLUG}-cache" >> $GITHUB_ENV
    - name: Print Branch Name
      run: |
        echo "Branch name is : ${BRANCH_NAME}"

